name: lints_y
description: "Lint rules for Project Y."
version: 0.1.0
repository: https://github.com/Yogi-7y/Project-Y.git
homepage: https://github.com/Yogi-7y/Project-Y/tree/main/packages/lints

environment:
  sdk: ">=3.2.6 <4.0.0"


