name: project_y
repository: https://github.com/Yogi-7y/Project-Y
sdkPath: .fvm/flutter_sdk

packages:
  - packages/*

ide:
  intellij: 
    enabled: false

command:
  version:
    includeScopes: false
    workspaceChangelog: false

    hooks:
      post: dart run scripts/format_changelog.dart

scripts:
  analyze:
    exec: dart analyze .
  
  release_core_y:
    description: "Version and Publish core_y"
    run: |
      melos version --scope="core_y" --yes &&
      melos publish --scope="core_y" --no-dry-run &&
      git push --follow-tags