name: network_y
description: "Network package for Project Y."
version: 0.0.2

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_y: ^0.0.2

  dio: ^5.4.1

  flutter:
    sdk: flutter

  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints_y: ^0.0.1

  mocktail: ^1.0.3

flutter:
