name: network_y
description: "Network package for Project Y."
version: 0.1.3
repository: https://github.com/Yogi-7y/Project-Y.git
homepage: https://github.com/Yogi-7y/Project-Y/tree/main/packages/network

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  core_y: ^0.3.1
  dio: ^5.4.1

  meta: ^1.10.0

dev_dependencies:
  lints_y: ^0.0.1

  mocktail: ^1.0.4
  test: ^1.25.2
