name: network_y
description: "Network package for Project Y."
version: 0.0.1

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/core
      ref: core_v1.0.2

  dio: ^5.4.1

  flutter:
    sdk: flutter

  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/lints
      ref: lints_v1.0.0

  mocktail: ^1.0.3

flutter:
