name: core_y
description: "A new Flutter package project."
version: 0.0.3

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  lints_y: ^0.0.1
  test: ^1.25.2

flutter:
