name: core_y
description: Core utilities for Project-Y
version: 0.0.4+1
repository: https://github.com/Yogi-7y/Project-Y.git
homepage: https://github.com/Yogi-7y/Project-Y/tree/main/packages/core

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints_y: ^0.0.1
  test: ^1.25.2
